BRANRD-5/update_style
Spacus1k/BarCodeScanner pull request #8
Opened 2021-08-06 19:16 UTC by Spacus1k

2021-08-19 07:32 UTC, Vinny94051 requested changes
Не так уж и плохо на самом деле

2021-08-19 07:32 UTC, Vinny94051 commented on presentation/src/main/java/ru/shpak/presentation/fragments/ClickedItemFragment.kt
> +class ClickedItemFragment(private val barCode: BarCode) :
Назва фрагмента не понятная

2021-08-19 07:32 UTC, Vinny94051 commented on presentation/src/main/java/ru/shpak/presentation/utils/ActionHelper.kt
> +fun deleteItemAction(
Не понимаю что это. Не нужно выносить НЕ общие методы в файлы. Ибо я рил не выкупаю к чему он относится, как и все методы тут.

2021-08-28 20:32 UTC, Spacus1k commented on data/build.gradle
> +    api "androidx.room:room-runtime:$room_version"
Потому что 
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

2021-09-03 15:23 UTC, Vinny94051 approved these changes

2021-09-03 15:23 UTC, Vinny94051 commented on presentation/src/main/java/ru/shpak/presentation/fragments/ClickedBarCodeFragment.kt
> +    private fun searchNet(barCode: BarCode) {
хуево

2021-09-03 15:23 UTC, Vinny94051 commented on presentation/src/main/java/ru/shpak/presentation/fragments/HistoryFragment.kt
> +    private var router: Router? = null
```suggestion
    private var router: Router by lazy { Router(requireActivity(), R.id.activity_fragment_container)  }
```

2021-09-03 15:23 UTC, Vinny94051 commented on presentation/src/main/java/ru/shpak/presentation/utils/Router.kt
> +class Router constructor(private val activity: FragmentActivity, private val containerViewId: Int) {
Передать FragmentManager сразу

2021-09-03 16:29 UTC, merged